CREATE TABLE admin (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE student (
  student_id INTEGER PRIMARY KEY AUTOINCREMENT,
  first_name TEXT UNIQUE NOT NULL,
  last_name TEXT NOT NULL
);

CREATE TABLE quiz (
  quiz_id INTEGER PRIMARY KEY AUTOINCREMENT,
  subject TEXT UNIQUE NOT NULL,
  questions INTEGER NOT NULL,
  quiz_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
